version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webmvc-tomcat-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webmvc-tomcat-kotlin
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webmvc-jetty-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webmvc-undertow-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webflux-tomcat-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webflux-jetty-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: maven
    directory: /examples/webflux-undertow-java
    schedule:
      interval: daily
    labels:
      - type:dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - type:dependencies
